### ISSUE TITLE
React rendering issue with material-ui library

### ISSUE THREAD

**Issue by jigar288** [acm-uic/roll-call#2]
React Cards Issue Description:

I’m having an issue with React and using the material-ui library. My cards are getting rendered vertically instead of side by side horizontally. 

![Screen Shot 2019-12-30 at 3 54 29 PM](https://user-images.githubusercontent.com/21162408/71602858-bc382c80-2b1f-11ea-834b-dd9632efbbdb.png)

![Screen Shot 2019-12-28 at 2 26 06 PM](https://user-images.githubusercontent.com/21162408/71602882-e5f15380-2b1f-11ea-85e1-ffeb588c2350.png)

Here is the original code that perfectly renders cards side by side:  https://github.com/acm-uic/roll-call/blob/feature/home-page/src/App.tsx

I modified the original code since I had to fetch data for the cards. Here is the modified version in two separate files (Event.tsx & Events.tsx): https://github.com/acm-uic/roll-call/tree/feature/printEvents/src/components

I tried messing around with the grid but it didn’t help.

**Comment by alx168** [comment]
Tried to reproduce this bug. Messed around with number of cards being loaded and couldn't get anything. Messed around with margins and also couldn't get this bug. More details needed?

**Comment by anarmawala** [comment]
Fixed with commit 55c15dd
